stages:
    - test
    - build
    - deploy

image: openjdk:8-alpine
    
test:
    tags:
        - DalOpenStack
    stage: test
    script:
        - echo "Testing"
        - sh mvnw compile
        - sh mvnw test
        
        
        
build:
    tags:
        - DalOpenStack
    stage: build
    script:
        - echo "Building"
        - sh mvnw clean
        - sh mvnw install
        - ls target
    artifacts:
        paths:
            - target/*.jar
            
            


deploy:
    tags:
        - DalOpenStack
    stage: deploy
    script:
        - echo "Deploying"
        - ls target
