stages:
    - test
    - build
    - deploy

image: openjdk:8-alpine
    
test:
    tags:
        - ugrad
    stage: test
    script:
        - echo "Testing"
        - sh mvnw compile
        - sh mvnw test
        
        
        
build:
    tags:
        - ugrad
    stage: build
    script:
        - echo "Building"
        - sh mvnw clean
        - sh mvnw install
        - ls target
    artifacts:
        paths:
            - target/*.jar
            
            


deploy:
    tags:
        - DalOpenStack
    stage: deploy
    
    before_script:
        - ls target
        - docker container stop group14_project || exit_code=$?
        - if [ $exit_code -ne 0 ]; then echo "container does not exist"; fi;
        - docker container rm group14_project || exit_code=$?
        - if [ $exit_code -ne 0 ]; then echo "container does not exist"; fi;
    script:
        - echo "Deploying"        
        - docker build -t group14_project .
        - docker images
        - docker run -p 8080:8080 -d --name group14_project group14_project
        
    after_script:
        - docker ps
        - ifconfig
        - docker logs group14_project

