stages:
    - test
    - build
    - deploy

image: openjdk:8-alpine

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    GIT_STRATEGY: clone
    
test:
    tags:
        - $GITLAB_RUNNER_TAG
    stage: test
    script:
        - echo "Testing"
        - sh gradlew check test
        
        
        
build:
    tags:
        - $GITLAB_RUNNER_TAG
    stage: build
    script:
        - echo "Building"
        - sh gradlew clean build
        - ls build/libs
    artifacts:
        paths:
            - build/libs/*.jar
            
            


deploy:
    tags:
        - DalOpenStack
    stage: deploy
    only:
        - develop
        
    before_script:
        - ls build/libs
        - docker container stop group14_project || exit_code=$?
        - if [ $exit_code -ne 0 ]; then echo "container does not exist"; fi;
        - docker container rm group14_project || exit_code=$?
        - if [ $exit_code -ne 0 ]; then echo "container does not exist"; fi;
    script:
        - echo "Deploying"        
        - docker build -t group14_project .
        - docker images
        - docker run -p 8080:8080 -d --name group14_project group14_project
        
    after_script:
        - docker ps
        - ifconfig
        - sleep 20
        - docker logs group14_project
        
#    when: manual

