spring:
  profiles:
    active: ${APP_PROFILE:dev}

server:
  port: ${PORT:8080} 


---
spring:
  application:
    name: group14-project
  profiles: dev
  mail:
    host: smtp.gmail.com
    username: group14sdc@gmail.com
    password: Group14SDC
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_14_DEVINT
    username: CSCI5308_14_DEVINT_USER
    password: CSCI5308_14_DEVINT_14103

---

spring:
  application:
    name: group14-project
  profiles: test
  mail:
    host: smtp.gmail.com
    username: group14sdc@gmail.com
    password: Group14SDC
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_14_TEST
    username: CSCI5308_14_TEST_USER
    password: CSCI5308_14_TEST_14577
  
---

spring:
  application:
    name: group14-project
  profiles: prod
  mail:
    host: smtp.gmail.com
    username: group14sdc@gmail.com
    password: Group14SDC
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_14_PRODUCTION
    username: CSCI5308_14_PRODUCTION_USER
    password: CSCI5308_14_PRODUCTION_14739
